/*
 *
 * ApplicationForm constants
 *
 */

export const DEFAULT_ACTION = 'app/ApplicationForm/DEFAULT_ACTION';
export const SET_ON_CHANGE_APPLICANT_INFO = 'app/ApplicationForm/SET_ON_CHANGE_APPLICANT_INFO';
export const SET_ON_CHANGE_APPLICANT_NAME = 'app/ApplicationForm/SET_ON_CHANGE_APPLICANT_NAME';
export const SET_ON_CHANGE_GENDER = 'app/ApplicationForm/SET_ON_CHANGE_GENDER';
export const SET_ON_CHANGE_RELIGION = 'app/ApplicationForm/SET_ON_CHANGE_RELIGION';
export const SET_ON_CHANGE_DOB = 'app/ApplicationForm/SET_ON_CHANGE_DOB';
export const SET_ON_CHANGE_BIRTH_CERTIFICATE_NO = 'app/ApplicationForm/SET_ON_CHANGE_BIRTH_CERTIFICATE_NO';
export const SET_ON_CHANGE_QUOTA = 'app/ApplicationForm/SET_ON_CHANGE_QUOTA';
export const SET_ON_CHANGE_File_NAME = 'app/ApplicationForm/SET_ON_CHANGE_File_NAME';
export const SET_ON_CHANGE_File_CONTENT = 'app/ApplicationForm/SET_ON_CHANGE_File_CONTENT';
export const SET_ON_CHANGE_File_SAVE = 'app/ApplicationForm/SET_ON_CHANGE_File_SAVE';
export const SET_ON_CHANGE_MOBILE_NO = 'app/ApplicationForm/SET_ON_CHANGE_MOBILE_NO';
export const SET_ON_CHANGE_ADDRERSS = 'app/ApplicationForm/SET_ON_CHANGE_ADDRERSS';

export const SET_ON_CHANGE_FATHER_NAME = 'app/ApplicationForm/SET_ON_CHANGE_FATHER_NAME';
export const SET_ON_CHANGE_FATHER_OCCUPATION = 'app/ApplicationForm/SET_ON_CHANGE_FATHER_OCCUPATION';
export const SET_ON_CHANGE_FATHER_NID_NO = 'app/ApplicationForm/SET_ON_CHANGE_FATHER_NID_NO';
export const SET_ON_CHANGE_MOTHER_NAME = 'app/ApplicationForm/SET_ON_CHANGE_MOTHER_NAME';
export const SET_ON_CHANGE_MOTHER_OCCUPATION = 'app/ApplicationForm/SET_ON_CHANGE_MOTHER_OCCUPATION';
export const SET_ON_CHANGE_MOTHER_NID_NO = 'app/ApplicationForm/SET_ON_CHANGE_MOTHER_NID_NO';

export const SET_ON_CHANGE_INSTITUTE_NAME = 'app/ApplicationForm/SET_ON_CHANGE_INSTITUTE_NAME';
export const SET_ON_CHANGE_INSTITUTE_TYPE = 'app/ApplicationForm/SET_ON_CHANGE_INSTITUTE_TYPE';
export const SET_ON_CHANGE_BOARD_NAME = 'app/ApplicationForm/SET_ON_CHANGE_BOARD_NAME';
export const SET_ON_CHANGE_CLASS_NAME = 'app/ApplicationForm/SET_ON_CHANGE_CLASS_NAME';
export const SET_ON_CHANGE_ROLL_NO = 'app/ApplicationForm/SET_ON_CHANGE_ROLL_NO';
export const SET_ON_CHANGE_REGISTRATION_NO = 'app/ApplicationForm/SET_ON_CHANGE_REGISTRATION_NO';
export const SET_ON_CHANGE_EXAM_NAME = 'app/ApplicationForm/SET_ON_CHANGE_EXAM_NAME';
export const SET_ON_CHANGE_EXAM_GRADE = 'app/ApplicationForm/SET_ON_CHANGE_EXAM_GRADE';
export const SET_ON_CHANGE_EXAM_GPA = 'app/ApplicationForm/SET_ON_CHANGE_EXAM_GPA';
export const SET_ON_CHANGE_PASSING_YEAR = 'app/ApplicationForm/SET_ON_CHANGE_PASSING_YEAR';

export const SET_ON_SUBMIT_ADDITIONAL_INFO = 'app/ApplicationForm/SET_ON_SUBMIT_ADDITIONAL_INFO';
export const SET_ON_SUBMIT_INSERT_APPLICANT_INFO = 'app/ApplicationForm/SET_ON_SUBMIT_INSERT_APPLICANT_INFO';


// SET_ON_CHANGE_File_CONTENT
// SET_ON_CHANGE_INSTITUTE_NAME
// SET_ON_CHANGE_INSTITUTE_TYPE
// SET_ON_CHANGE_BOARD_NAME
// SET_ON_CHANGE_CLASS_NAME
// SET_ON_CHANGE_ROLL_NO
// SET_ON_CHANGE_REGISTRATION_NO
// SET_ON_CHANGE_EXAM_NAME
// SET_ON_CHANGE_EXAM_GRADE
// SET_ON_CHANGE_EXAM_GPA
// SET_ON_CHANGE_PASSING_YEAR

// SET_ON_CHANGE_INSERT_APPLICANT_INFO